### ISSUE TITLE
issues with kobold

### ISSUE THREAD

**Issue by goldengio16** [agnaistic/agnai#82]
Why do I get a fail to generate response "Unproccesable entity"? Is there something wrong on my end or is this a bug.
![Screenshot 2023-03-24 220409](https://user-images.githubusercontent.com/128877785/227689488-9a6523d5-1dc5-4995-bb9c-4e9c8d3f5827.png)

**Comment by sceuick** [comment]
I haven't had this happen to me for a whlie. From memory I ended up having to restart Kobold. I'm not sure of the cause. It could be that something Kobold retains in memory is no longer valid.

**Comment by sceuick** [comment]
I've pushed a fix to ensure there are no blank lines between messages.
_Hopefully_ that fixes the issue or at least improves it. This may be related to removing the `\n\n` end token.
I have a suspicion  that non-LLaMa/Alpaca models may want that end token present.

**Comment by sceuick** [comment]
Okay, the issue was caused by a property being sent in the payload to Kobold that didn't belong there.
It was being added to the other adapters as well which was not intended.

Thanks for reporting! Fix should be deployed in a minute or two.

**Comment by Shimmyshak** [comment]
[This individual](https://www.reddit.com/r/AgnAIstic/comments/14fh4bl/site_erases_api_from_kobold_url/) as well as i are still experiencing this isssue. I'm running koboldAI locally with remote_play.bat and pygmalion-1.3b. I experience this issue when running AgnAI locally and on the website. 
![image](https://github.com/agnaistic/agnai/assets/71646802/dfa61806-3457-4779-b71c-754750627eed)
