### ISSUE TITLE
Sampler order for NovelAI problems

### ISSUE THREAD

**Issue by cingorn** [agnaistic/agnai#826]
**Describe the bug**
When you're logged in and edit a NovelAI preset and change sampler order:
* changes are not saved, when the preset is reopened (it reverts to the default order), 
* trying to use the preset in a chat results in an error from NovelAI API: `("RepeatedLogitId: '%s' was repeated in 'order'", 'temperature')`

**To Reproduce**
1. Log in.
2. Create a new NovelAI preset.
3. Change the sampler order and save.
4. Reopen the preset, changes are not saved.
5. Create a new chat using the created preset.
6. Send a message, you either receive a NovelAI API error (when streaming is off) or the chat hangs waiting for the response (streaming on).

**Expected behavior**
* Preset changes are saved and cause no errors.

**Additional context**
* This happens only when you're logged in.
* When changing the sampler order, the saved order in the DB is an array of zeros: `[0, 0, ...]`
* When these zeros are sent to NovelAI API, it treats it as if temperature (id = 0) was repeated multiple times.

**Comment by sceuick** [comment]
Hopefully resolved now.

**Comment by Kalpira** [comment]
I'm sorry but at least on my end it's still not resolved 😭

When I change the sampler order and save it, it saves nicely. However, if I disable any sampler by hitting its respective icon at the bottom, save and then refresh the page, the sampler order goes back to being scrambled.

The samplers I try to disable are CFG Scale and Mirostat Tau, I don't know if that has any influence.

________________________________
